#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/lyriq

PRODUCT_COPY_FILES += \
    vendor/motorola/lyriq/proprietary/product/etc/permissions/privapp-permissions-com.google.android.euicc.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.google.android.euicc.xml \
    vendor/motorola/lyriq/proprietary/system/etc/permissions/moto-telephony.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-telephony.xml \
    vendor/motorola/lyriq/proprietary/system/etc/public.libraries-mtk.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-mtk.txt \
    vendor/motorola/lyriq/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc \
    vendor/motorola/lyriq/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/motorola/lyriq/proprietary/system_ext/etc/sysconfig/com.mediatek.ims.config.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/com.mediatek.ims.config.xml \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/031c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/031c0000000000000000000000000000.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/031c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/031c0000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/05060000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05060000000000000000000000000000.tabin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/05070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05070000000000000000000000000000.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/05070000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05070000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/07210000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07210000000000000000000000000000.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/07210000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07210000000000000000000000000000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/6b3f5fa0f8cf55a7be2582587d62d63a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/6b3f5fa0f8cf55a7be2582587d62d63a.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.drbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9073f03a9618383bb1856eb3f990babd.tlbin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/98fb95bcb4bf42d26473eae48690d7ea.tabin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/motorola/lyriq/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000003.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000003.tabin \
    vendor/motorola/lyriq/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ap_gain.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain.bin \
    vendor/motorola/lyriq/proprietary/vendor/etc/ap_gain_mmul.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain_mmul.bin \
    vendor/motorola/lyriq/proprietary/vendor/etc/apdb/APDB_MT6885_S01__W2506:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6885_S01__W2506 \
    vendor/motorola/lyriq/proprietary/vendor/etc/apdb/APDB_MT6885_S01__W2506_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6885_S01__W2506_ENUM \
    vendor/motorola/lyriq/proprietary/vendor/etc/aualgo/aualgo_arp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/aualgo/aualgo_arp.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/aualgo/aualgo_azp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/aualgo/aualgo_azp.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechAcousticShock_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechAcousticShock_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechAcousticShock_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechAcousticShock_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWCommonSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCommonSetting_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWCommonSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCommonSetting_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWCompatibilityCode_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCompatibilityCode_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWCompatibilityCode_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCompatibilityCode_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/aurisys_config_rv.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_rv.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/camera/vidhance.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance.lic \
    vendor/motorola/lyriq/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/motorola/lyriq/proprietary/vendor/etc/cust_color_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_0.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/cust_color_1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_1.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Bell_Mobility.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Bell_Mobility.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Blue_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Blue_Wireless.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Boost_Mobile.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Boost_Mobile.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_C_Spire_NL.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_C_Spire_NL.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_C_Spire_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_C_Spire_US.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Carolina_West_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Carolina_West_Wireless.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Dish.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Dish.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_FirstNet.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_FirstNet.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Inland_Cellular.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Inland_Cellular.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_MobileNation.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_MobileNation.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Argentina.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Argentina.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Movistar_Peru.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_NexTech_Ota.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_NexTech_Ota.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Nextel_Communications.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Nextel_Communications.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_No_Carrier_ID_LPP_Profile_11.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_No_Carrier_ID_LPP_Profile_11.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_No_Carrier_ID_LPP_Profile_7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_No_Carrier_ID_LPP_Profile_7.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_PTCI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_PTCI.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Pine_Belt.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Pine_Belt.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_TELUS_Mobility.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_TELUS_Mobility.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_USC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_USC.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Virgin_Mobile.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Virgin_Mobile.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_nTelos.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_nTelos.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/gralloc/vpu.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/vpu.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/init.insmod.mt6893.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.mt6893.cfg \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint-service-goodix.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint-service-goodix.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/android.hardware.drm-service.clearkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.clearkey.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/android.hardware.graphics.allocator-V2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator-V2-service-mediatek.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/bootperf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/bootperf.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/hw/init.mmi.backup.trustlet.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mmi.backup.trustlet.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/init.lyriq.nfc.conf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lyriq.nfc.conf.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/init.lyriq.nfc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.lyriq.nfc.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/memtrack-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/memtrack-mediatek.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/motorola.hardware.camera.imgtuner.aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.camera.imgtuner.aidl-service.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/nfc-service-nxp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nfc-service-nxp.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/secure_element-service-nxp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secure_element-service-nxp.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/vendor.mmi.carrier.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mmi.carrier.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/vibrator-mtk-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vibrator-mtk-default.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/motorola/lyriq/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/libnfc-nxp-PN560.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-PN560.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/libnfc-nxp-SN220E.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-SN220E.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/libnfc-nxp-SN220P.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-SN220P.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/mot_spn_table:$(TARGET_COPY_OUT_VENDOR)/etc/mot_spn_table \
    vendor/motorola/lyriq/proprietary/vendor/etc/motorola/sensors/mot_sensor_settings.json:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/sensors/mot_sensor_settings.json \
    vendor/motorola/lyriq/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/motorola/lyriq/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/motorola/lyriq/proprietary/vendor/etc/permissions/com.mediatek.hardware.vow_dsp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.mediatek.hardware.vow_dsp.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/permissions/com.nxp.mifare.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.nxp.mifare.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/permissions/unavail.android.hardware.sensor.barometer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/unavail.android.hardware.sensor.barometer.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/motorola/lyriq/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/motorola/lyriq/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/motorola/lyriq/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/motorola/lyriq/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/motorola/lyriq/proprietary/vendor/etc/seccomp_policy/mediaswcodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaswcodec.policy \
    vendor/motorola/lyriq/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/motorola/lyriq/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/vhw.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vhw.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/motorola/lyriq/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/motorola/lyriq/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/motorola/lyriq/proprietary/vendor/firmware/WIFI_RAM_CODE_soc3_0_1a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc3_0_1a_1.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_haptic.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_osc_rtp_12K_10s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_osc_rtp_12K_10s.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Argo_Navis.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Argo_Navis.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Attentive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Attentive.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Awake.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Awake.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Bird_Loop.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Bird_Loop.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Brilliant_Times.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Brilliant_Times.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Chimey_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Chimey_Phone.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_City_Lights.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_City_Lights.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Complex.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Complex.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Crazy_Dream.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Crazy_Dream.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Curve_Ball_Blend.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Curve_Ball_Blend.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Digital_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Digital_Phone.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Electrovision.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Electrovision.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Ether_Shake.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Ether_Shake.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Fateful_Words.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Fateful_Words.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Firefly.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Firefly.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Flutey_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Flutey_Phone.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Future_Funk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Future_Funk.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Future_Hi_Tech.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Future_Hi_Tech.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Girtab.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Girtab.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Hello.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Hello.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Hexagon.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Hexagon.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Hydra.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Hydra.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Insert_Coin.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Insert_Coin.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Jumping_Dots.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Jumping_Dots.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Keys.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Keys.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Loopy.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Loopy.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Loopy_Lounge.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Loopy_Lounge.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Modular.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Modular.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Momentum.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Momentum.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Morning.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Morning.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Moto.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Moto.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Moto_Original.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Moto_Original.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Moto_Retro.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Moto_Retro.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Natural.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Natural.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_New_Player.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_New_Player.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Now_or_Never.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Now_or_Never.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Onward.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Onward.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Organ_Dub.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Organ_Dub.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Overclocked.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Overclocked.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Pegasus.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Pegasus.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Play.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Play.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Pyxis.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Pyxis.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Regrade.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Regrade.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Scarabaeus.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Scarabaeus.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Sceptrum.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Sceptrum.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Simple.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Simple.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Solarium.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Solarium.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Sparse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Sparse.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Terrabytes.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Terrabytes.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Verizon_Airwaves.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Verizon_Airwaves.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw8622x_rtp_Zero_Hour.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8622x_rtp_Zero_Hour.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_acf.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/boe_goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/boe_goodix_cfg_group.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/boe_goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/boe_goodix_firmware.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/boe_goodix_test_limits_255.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/boe_goodix_test_limits_255.csv \
    vendor/motorola/lyriq/proprietary/vendor/firmware/connfem.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/connfem.cfg \
    vendor/motorola/lyriq/proprietary/vendor/firmware/conninfra.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/conninfra.cfg \
    vendor/motorola/lyriq/proprietary/vendor/firmware/cps4038.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cps4038.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/motorola/lyriq/proprietary/vendor/firmware/mm8013c_fw.hex:$(TARGET_COPY_OUT_VENDOR)/firmware/mm8013c_fw.hex \
    vendor/motorola/lyriq/proprietary/vendor/firmware/mm8013c_parameter_0101.hex:$(TARGET_COPY_OUT_VENDOR)/firmware/mm8013c_parameter_0101.hex \
    vendor/motorola/lyriq/proprietary/vendor/firmware/mm8013c_parameter_0103.hex:$(TARGET_COPY_OUT_VENDOR)/firmware/mm8013c_parameter_0103.hex \
    vendor/motorola/lyriq/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/motorola/lyriq/proprietary/vendor/firmware/soc3_0_patch_wmmcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_patch_wmmcu_1a_1_hdr.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/soc3_0_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_bt_1_1_hdr.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/soc3_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_bt_1a_1_hdr.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/soc3_0_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_1_1_hdr.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/soc3_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_1a_1_hdr.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/soc3_0_ram_mcu_e1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_mcu_e1_hdr.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/soc3_0_ram_wifi_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_wifi_1a_1_hdr.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/soc3_0_ram_wmmcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc3_0_ram_wmmcu_1a_1_hdr.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/tm_goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tm_goodix_cfg_group.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/tm_goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tm_goodix_firmware.bin \
    vendor/motorola/lyriq/proprietary/vendor/firmware/tm_goodix_test_limits_255.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/tm_goodix_test_limits_255.csv \
    vendor/motorola/lyriq/proprietary/vendor/firmware/txpowerctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl.cfg \
    vendor/motorola/lyriq/proprietary/vendor/firmware/valhall-1691526.wa:$(TARGET_COPY_OUT_VENDOR)/firmware/valhall-1691526.wa \
    vendor/motorola/lyriq/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/motorola/lyriq/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg

PRODUCT_PACKAGES += \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    com.motorola.hardware.biometric.fingerprint-V2-ndk \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    fingerprint.goodix.default \
    sound_trigger.primary.default \
    vendor.mediatek.hardware.videotelephony-impl \
    vibrator.default \
    libAVCSecureVencCA \
    libCamera_motlyriqhi1336mipiraw_ArcSoft_Raw_NV_Capture \
    libCamera_motlyriqhi1336mipiraw_ArcSoft_Raw_NV_Face_Capture \
    libCamera_motlyriqhi1336mipiraw_ArcSoft_Raw_NV_Preview \
    libCamera_motlyriqhi1336mipiraw_Bokeh_Capture \
    libCamera_motlyriqhi1336mipiraw_E2EHDR_Preview \
    libCamera_motlyriqhi1336mipiraw_E2EHDR_Video \
    libCamera_motlyriqhi1336mipiraw_Face_Capture \
    libCamera_motlyriqhi1336mipiraw_Face_Preview \
    libCamera_motlyriqhi1336mipiraw_Flash_Capture \
    libCamera_motlyriqhi1336mipiraw_Flash_Preview \
    libCamera_motlyriqhi1336mipiraw_HDR_Capture \
    libCamera_motlyriqhi1336mipiraw_HDR_Face_Capture \
    libCamera_motlyriqhi1336mipiraw_ITS_Capture \
    libCamera_motlyriqhi1336mipiraw_ITS_Preview \
    libCamera_motlyriqhi1336mipiraw_P1_YUV \
    libCamera_motlyriqhi1336mipiraw_Scene_3rd_party_Preview \
    libCamera_motlyriqhi1336mipiraw_Scene_3rd_party_ZOOM \
    libCamera_motlyriqhi1336mipiraw_Scene_Capture \
    libCamera_motlyriqhi1336mipiraw_Scene_Preview \
    libCamera_motlyriqhi1336mipiraw_Scene_YUV_Reprocess \
    libCamera_motlyriqhi1336mipiraw_Video_1080 \
    libCamera_motlyriqhi1336mipiraw_Video_4K \
    libCamera_motlyriqhi1336mipiraw_Video_Capture \
    libCamera_motlyriqhi1336mipiraw_Video_Capture_2X \
    libCamera_motlyriqhi1336mipiraw_Zoom_Capture_2X \
    libCamera_motlyriqhi1336mipiraw_Zoom_Preview_2X \
    libCamera_motlyriqhi1336mipirawrow_ArcSoft_Raw_NV_Capture \
    libCamera_motlyriqhi1336mipirawrow_ArcSoft_Raw_NV_Face_Capture \
    libCamera_motlyriqhi1336mipirawrow_ArcSoft_Raw_NV_Preview \
    libCamera_motlyriqhi1336mipirawrow_Bokeh_Capture \
    libCamera_motlyriqhi1336mipirawrow_E2EHDR_Preview \
    libCamera_motlyriqhi1336mipirawrow_E2EHDR_Video \
    libCamera_motlyriqhi1336mipirawrow_Face_Capture \
    libCamera_motlyriqhi1336mipirawrow_Face_Preview \
    libCamera_motlyriqhi1336mipirawrow_Flash_Capture \
    libCamera_motlyriqhi1336mipirawrow_Flash_Preview \
    libCamera_motlyriqhi1336mipirawrow_HDR_Capture \
    libCamera_motlyriqhi1336mipirawrow_HDR_Face_Capture \
    libCamera_motlyriqhi1336mipirawrow_ITS_Capture \
    libCamera_motlyriqhi1336mipirawrow_ITS_Preview \
    libCamera_motlyriqhi1336mipirawrow_P1_YUV \
    libCamera_motlyriqhi1336mipirawrow_Scene_3rd_party_Preview \
    libCamera_motlyriqhi1336mipirawrow_Scene_3rd_party_ZOOM \
    libCamera_motlyriqhi1336mipirawrow_Scene_Capture \
    libCamera_motlyriqhi1336mipirawrow_Scene_Preview \
    libCamera_motlyriqhi1336mipirawrow_Scene_YUV_Reprocess \
    libCamera_motlyriqhi1336mipirawrow_Video_1080 \
    libCamera_motlyriqhi1336mipirawrow_Video_4K \
    libCamera_motlyriqhi1336mipirawrow_Video_Capture \
    libCamera_motlyriqhi1336mipirawrow_Video_Capture_2X \
    libCamera_motlyriqhi1336mipirawrow_Zoom_Capture_2X \
    libCamera_motlyriqhi1336mipirawrow_Zoom_Preview_2X \
    libCamera_motlyriqov32bmipiraw_ArcSoft_Raw_NV_Capture \
    libCamera_motlyriqov32bmipiraw_ArcSoft_Raw_NV_Face_Capture \
    libCamera_motlyriqov32bmipiraw_ArcSoft_Raw_NV_Flash_Capture \
    libCamera_motlyriqov32bmipiraw_ArcSoft_Raw_NV_Flash_Preview \
    libCamera_motlyriqov32bmipiraw_ArcSoft_Raw_NV_Preview \
    libCamera_motlyriqov32bmipiraw_Bokeh_Capture \
    libCamera_motlyriqov32bmipiraw_Display_Flash_Capture \
    libCamera_motlyriqov32bmipiraw_E2EHDR_Preview \
    libCamera_motlyriqov32bmipiraw_E2EHDR_Video \
    libCamera_motlyriqov32bmipiraw_Face_Capture \
    libCamera_motlyriqov32bmipiraw_HDR_Capture \
    libCamera_motlyriqov32bmipiraw_HDR_Face_Capture \
    libCamera_motlyriqov32bmipiraw_ITS_Capture \
    libCamera_motlyriqov32bmipiraw_ITS_Preview \
    libCamera_motlyriqov32bmipiraw_P1_YUV \
    libCamera_motlyriqov32bmipiraw_Scene_3rd_party_1280 \
    libCamera_motlyriqov32bmipiraw_Scene_3rd_party_1920 \
    libCamera_motlyriqov32bmipiraw_Scene_3rd_party_640 \
    libCamera_motlyriqov32bmipiraw_Scene_3rd_party_Capture \
    libCamera_motlyriqov32bmipiraw_Scene_3rd_party_ZOOM \
    libCamera_motlyriqov32bmipiraw_Scene_Capture \
    libCamera_motlyriqov32bmipiraw_Scene_Preview \
    libCamera_motlyriqov32bmipiraw_Scene_YUV_Reprocess \
    libCamera_motlyriqov32bmipiraw_Video_1080 \
    libCamera_motlyriqov32bmipiraw_Video_4K \
    libCamera_motlyriqov32bmipiraw_Video_Capture \
    libCamera_motlyriqov32bmipirawrow_ArcSoft_Raw_NV_Capture \
    libCamera_motlyriqov32bmipirawrow_ArcSoft_Raw_NV_Face_Capture \
    libCamera_motlyriqov32bmipirawrow_ArcSoft_Raw_NV_Flash_Capture \
    libCamera_motlyriqov32bmipirawrow_ArcSoft_Raw_NV_Flash_Preview \
    libCamera_motlyriqov32bmipirawrow_ArcSoft_Raw_NV_Preview \
    libCamera_motlyriqov32bmipirawrow_Bokeh_Capture \
    libCamera_motlyriqov32bmipirawrow_Display_Flash_Capture \
    libCamera_motlyriqov32bmipirawrow_E2EHDR_Preview \
    libCamera_motlyriqov32bmipirawrow_E2EHDR_Video \
    libCamera_motlyriqov32bmipirawrow_Face_Capture \
    libCamera_motlyriqov32bmipirawrow_HDR_Capture \
    libCamera_motlyriqov32bmipirawrow_HDR_Face_Capture \
    libCamera_motlyriqov32bmipirawrow_ITS_Capture \
    libCamera_motlyriqov32bmipirawrow_ITS_Preview \
    libCamera_motlyriqov32bmipirawrow_P1_YUV \
    libCamera_motlyriqov32bmipirawrow_Scene_3rd_party_1280 \
    libCamera_motlyriqov32bmipirawrow_Scene_3rd_party_1920 \
    libCamera_motlyriqov32bmipirawrow_Scene_3rd_party_640 \
    libCamera_motlyriqov32bmipirawrow_Scene_3rd_party_Capture \
    libCamera_motlyriqov32bmipirawrow_Scene_3rd_party_ZOOM \
    libCamera_motlyriqov32bmipirawrow_Scene_Capture \
    libCamera_motlyriqov32bmipirawrow_Scene_Preview \
    libCamera_motlyriqov32bmipirawrow_Scene_YUV_Reprocess \
    libCamera_motlyriqov32bmipirawrow_Video_1080 \
    libCamera_motlyriqov32bmipirawrow_Video_4K \
    libCamera_motlyriqov32bmipirawrow_Video_Capture \
    libCamera_motlyriqov50amipiraw_50_Capture \
    libCamera_motlyriqov50amipiraw_ArcSoft_Raw_NV_Capture \
    libCamera_motlyriqov50amipiraw_ArcSoft_Raw_NV_Face_Capture \
    libCamera_motlyriqov50amipiraw_ArcSoft_Raw_NV_Preview \
    libCamera_motlyriqov50amipiraw_Bokeh_Capture \
    libCamera_motlyriqov50amipiraw_E2EHDR_Preview \
    libCamera_motlyriqov50amipiraw_E2EHDR_Video \
    libCamera_motlyriqov50amipiraw_Face_Capture \
    libCamera_motlyriqov50amipiraw_Face_Preview \
    libCamera_motlyriqov50amipiraw_Flash_Capture \
    libCamera_motlyriqov50amipiraw_Flash_Preview \
    libCamera_motlyriqov50amipiraw_HDR_Capture \
    libCamera_motlyriqov50amipiraw_HDR_Face_Capture \
    libCamera_motlyriqov50amipiraw_ITS_Capture \
    libCamera_motlyriqov50amipiraw_ITS_Preview \
    libCamera_motlyriqov50amipiraw_P1_YUV \
    libCamera_motlyriqov50amipiraw_Panorama \
    libCamera_motlyriqov50amipiraw_SR_Capture \
    libCamera_motlyriqov50amipiraw_Scene_3rd_party_1280 \
    libCamera_motlyriqov50amipiraw_Scene_3rd_party_1920 \
    libCamera_motlyriqov50amipiraw_Scene_3rd_party_640 \
    libCamera_motlyriqov50amipiraw_Scene_3rd_party_Capture \
    libCamera_motlyriqov50amipiraw_Scene_3rd_party_ZOOM \
    libCamera_motlyriqov50amipiraw_Scene_Capture \
    libCamera_motlyriqov50amipiraw_Scene_Preview \
    libCamera_motlyriqov50amipiraw_Scene_YUV_Reprocess \
    libCamera_motlyriqov50amipiraw_Slow_Motion \
    libCamera_motlyriqov50amipiraw_Slow_Motion_2X \
    libCamera_motlyriqov50amipiraw_Video_1080 \
    libCamera_motlyriqov50amipiraw_Video_1080_60fps \
    libCamera_motlyriqov50amipiraw_Video_1080_shdr \
    libCamera_motlyriqov50amipiraw_Video_1080_zoom \
    libCamera_motlyriqov50amipiraw_Video_4K \
    libCamera_motlyriqov50amipiraw_Video_4K_zoom \
    libCamera_motlyriqov50amipiraw_Video_Capture \
    libCamera_motlyriqov50amipiraw_Video_Capture_2X \
    libCamera_motlyriqov50amipiraw_Video_Capture_4X \
    libCamera_motlyriqov50amipiraw_Video_Capture_60fps \
    libCamera_motlyriqov50amipiraw_Video_bokeh \
    libCamera_motlyriqov50amipiraw_Zoom_Capture_2X \
    libCamera_motlyriqov50amipiraw_Zoom_Preview_4X \
    libCamera_motlyriqov50amipirawrow_50_Capture \
    libCamera_motlyriqov50amipirawrow_ArcSoft_Raw_NV_Capture \
    libCamera_motlyriqov50amipirawrow_ArcSoft_Raw_NV_Face_Capture \
    libCamera_motlyriqov50amipirawrow_ArcSoft_Raw_NV_Preview \
    libCamera_motlyriqov50amipirawrow_Bokeh_Capture \
    libCamera_motlyriqov50amipirawrow_E2EHDR_Preview \
    libCamera_motlyriqov50amipirawrow_E2EHDR_Video \
    libCamera_motlyriqov50amipirawrow_Face_Capture \
    libCamera_motlyriqov50amipirawrow_Face_Preview \
    libCamera_motlyriqov50amipirawrow_Flash_Capture \
    libCamera_motlyriqov50amipirawrow_Flash_Preview \
    libCamera_motlyriqov50amipirawrow_HDR_Capture \
    libCamera_motlyriqov50amipirawrow_HDR_Face_Capture \
    libCamera_motlyriqov50amipirawrow_ITS_Capture \
    libCamera_motlyriqov50amipirawrow_ITS_Preview \
    libCamera_motlyriqov50amipirawrow_P1_YUV \
    libCamera_motlyriqov50amipirawrow_Panorama \
    libCamera_motlyriqov50amipirawrow_SR_Capture \
    libCamera_motlyriqov50amipirawrow_Scene_3rd_party_1280 \
    libCamera_motlyriqov50amipirawrow_Scene_3rd_party_1920 \
    libCamera_motlyriqov50amipirawrow_Scene_3rd_party_640 \
    libCamera_motlyriqov50amipirawrow_Scene_3rd_party_Capture \
    libCamera_motlyriqov50amipirawrow_Scene_3rd_party_ZOOM \
    libCamera_motlyriqov50amipirawrow_Scene_Capture \
    libCamera_motlyriqov50amipirawrow_Scene_Preview \
    libCamera_motlyriqov50amipirawrow_Scene_YUV_Reprocess \
    libCamera_motlyriqov50amipirawrow_Slow_Motion \
    libCamera_motlyriqov50amipirawrow_Slow_Motion_2X \
    libCamera_motlyriqov50amipirawrow_Video_1080 \
    libCamera_motlyriqov50amipirawrow_Video_1080_60fps \
    libCamera_motlyriqov50amipirawrow_Video_1080_60fps_zoom \
    libCamera_motlyriqov50amipirawrow_Video_1080_shdr \
    libCamera_motlyriqov50amipirawrow_Video_1080_zoom \
    libCamera_motlyriqov50amipirawrow_Video_4K \
    libCamera_motlyriqov50amipirawrow_Video_4K_zoom \
    libCamera_motlyriqov50amipirawrow_Video_Capture \
    libCamera_motlyriqov50amipirawrow_Video_Capture_2X \
    libCamera_motlyriqov50amipirawrow_Video_Capture_4X \
    libCamera_motlyriqov50amipirawrow_Video_Capture_60fps \
    libCamera_motlyriqov50amipirawrow_Video_bokeh \
    libCamera_motlyriqov50amipirawrow_Video_bokeh_zoom \
    libCamera_motlyriqov50amipirawrow_Zoom_Capture_2X \
    libCamera_motlyriqov50amipirawrow_Zoom_Preview_4X \
    libCamera_motlyriqov50emipiraw_50_Capture \
    libCamera_motlyriqov50emipiraw_ArcSoft_Raw_NV_Capture \
    libCamera_motlyriqov50emipiraw_ArcSoft_Raw_NV_Face_Preview \
    libCamera_motlyriqov50emipiraw_ArcSoft_Raw_NV_Preview \
    libCamera_motlyriqov50emipiraw_Bokeh_Capture \
    libCamera_motlyriqov50emipiraw_E2EHDR_Preview \
    libCamera_motlyriqov50emipiraw_E2EHDR_Video \
    libCamera_motlyriqov50emipiraw_EIS_Slow_Motion \
    libCamera_motlyriqov50emipiraw_EIS_Slow_Motion_2X \
    libCamera_motlyriqov50emipiraw_Face_Capture \
    libCamera_motlyriqov50emipiraw_Face_Preview_ZSD \
    libCamera_motlyriqov50emipiraw_Flash_Capture \
    libCamera_motlyriqov50emipiraw_Flash_Preview \
    libCamera_motlyriqov50emipiraw_HDR_Capture \
    libCamera_motlyriqov50emipiraw_HDR_Face_Capture \
    libCamera_motlyriqov50emipiraw_Night_Vision_Capture \
    libCamera_motlyriqov50emipiraw_Night_Vision_Face_Capture \
    libCamera_motlyriqov50emipiraw_Night_Vision_Preview \
    libCamera_motlyriqov50emipiraw_P1_YUV \
    libCamera_motlyriqov50emipiraw_Panorama \
    libCamera_motlyriqov50emipiraw_Scene_3rd_party_Preview \
    libCamera_motlyriqov50emipiraw_Scene_3rd_party_ZOOM \
    libCamera_motlyriqov50emipiraw_Scene_Capture \
    libCamera_motlyriqov50emipiraw_Scene_Preview \
    libCamera_motlyriqov50emipiraw_Scene_Preview_ZSD \
    libCamera_motlyriqov50emipiraw_Scene_YUV_Reprocess \
    libCamera_motlyriqov50emipiraw_Slow_Motion \
    libCamera_motlyriqov50emipiraw_Slow_Motion_2X \
    libCamera_motlyriqov50emipiraw_Video_1080 \
    libCamera_motlyriqov50emipiraw_Video_1080_60fps \
    libCamera_motlyriqov50emipiraw_Video_1080_zoom \
    libCamera_motlyriqov50emipiraw_Video_Capture \
    libCamera_motlyriqov50emipiraw_Video_Capture_2X \
    libCamera_motlyriqov50emipiraw_Video_Capture_4X \
    libCamera_motlyriqov50emipiraw_Video_Capture_60fps \
    libCamera_motlyriqov50emipiraw_Zoom_Capture_2X \
    libCamera_motlyriqov50emipiraw_Zoom_Preview_2X \
    libDefaultFpsActor \
    libDxHdcp \
    libFrameRecord \
    libNoFpsActor \
    libOpenCL \
    libappgamepq \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libbwc \
    libcam.halsensor.hwintegration_mt6893 \
    libcapctrl \
    libcarrierconfig \
    libccci_util \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libconnfem \
    libcustom_nvram \
    libdre \
    libdynamiclog \
    libfile_op \
    libformatter \
    libged \
    libgf_hal \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libhdrvideo \
    libicd_decoder \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libladder \
    libminiui \
    libmml \
    libmmprofile \
    libmnetlink_v104 \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtklimiter_vendor \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtkshifter_vendor \
    libmvpu_config_data \
    libmvpu_wrapper \
    libneuroeara \
    libneuron_graph_delegate.mtk_vendor \
    libnir_neon_driver_ndk.mtk.vndk \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    liboem_specific \
    liboemcrypto \
    libpixelflinger \
    libpn560_fw \
    libpqframework \
    librgbwlightsensor \
    libsimlock \
    libsimmelock \
    libsysenv \
    libtflite_mtk_vendor \
    libthha \
    libudf \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libvibratorutils \
    libvpu \
    libvpu5 \
    libdrmclearkeyplugin \
    libmockdrmcryptoplugin \
    meta_wifi_data \
    libneuron_adapter_mgvi \
    libneuron_platform.vpu \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    libaal_key \
    libmp4enc_sa.ca7 \
    libvpudv3a_vcodec \
    vendor.mediatek.hardware.apmonitor@2.0 \
    vendor.mediatek.hardware.rcs@2.0 \
    android.hardware.biometrics.common-V3-ndk \
    android.hardware.biometrics.fingerprint-V3-ndk \
    android.hardware.camera.common-V1-ndk \
    android.hardware.camera.common-V2-ndk \
    android.hardware.camera.common@1.0 \
    android.hardware.camera.device-V3-ndk \
    android.hardware.camera.device@1.0 \
    android.hardware.camera.device@3.2 \
    android.hardware.camera.device@3.3 \
    android.hardware.camera.device@3.4 \
    android.hardware.camera.device@3.5 \
    android.hardware.camera.device@3.6 \
    android.hardware.camera.metadata-V3-ndk \
    android.hardware.camera.provider-V3-ndk \
    android.hardware.camera.provider@2.4 \
    android.hardware.camera.provider@2.5 \
    android.hardware.camera.provider@2.6 \
    android.hardware.drm-V1-ndk \
    android.hardware.nfc-V1-ndk \
    android.hardware.nfc@1.0 \
    android.hardware.nfc@1.1 \
    android.hardware.nfc@1.2 \
    android.hardware.secure_element-V1-ndk \
    android.hardware.secure_element@1.0 \
    android.hardware.vibrator-V2-ndk \
    ese_teq1_nxp_snxxx \
    android.hardware.audio.effect.aidl-impl-mediatek \
    android.hardware.bluetooth.audio@2.0-impl \
    android.hardware.bluetooth.audio@2.1-impl \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.sensors@2.X-subhal-mediatek \
    android.hardware.soundtrigger3-impl \
    android.hardware.soundtrigger@2.3-impl \
    android.hidl.memory@1.0-impl \
    audio.bluetooth.default \
    audio.primary.default \
    audio.primary.mt6893 \
    audio.r_submix.default \
    audio.r_submix.mt6893 \
    audio.usb.default \
    audio_policy.stub \
    audio_radar.primary.default \
    displaypanel.default \
    gps.default \
    gralloc.default \
    hwcomposer.mt6893 \
    libmbrainImpl \
    motorola.hardware.audio.radar2-impl \
    android.hardware.graphics.allocator-V2-mediatek \
    mapper.mediatek \
    power.default \
    sensors.dynamic_sensor_hal \
    sensors.mediatek.V2.0 \
    sensors.mt6893 \
    thermal_hal \
    tsa_hdcp_service-impl \
    vendor.mediatek.hardware.audio-impl \
    vendor.mediatek.hardware.bluetooth.audio@2.1-impl \
    vendor.mediatek.hardware.bluetooth.audio@2.2-impl \
    vendor.mediatek.hardware.camera.atms_aidl@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice_aidl@1.0-impl \
    vendor.mediatek.hardware.camera.isphal_aidl@1.0-impl \
    vendor.mediatek.hardware.camera.postproc_aidl@1.0-impl \
    vendor.mediatek.hardware.gnss-impl \
    vendor.mediatek.hardware.mtkpower-aidl-impl \
    vendor.mediatek.hardware.nvram-impl \
    vendor.mediatek.hardware.pq_aidl-impl \
    libDR \
    libJpgEncPipe \
    libMcClient \
    libMtkSpeechEnh \
    libMtkSpeechEnh_swb \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTEECommon \
    lib_iir \
    libacdk \
    libadropbox \
    libalsautils-v31 \
    libarcsoft_portrait_distortion_correction \
    libarcsoft_portrait_super_night_se_raw \
    libarcsoft_super_night_raw \
    libarcsoft_super_night_raw_bin \
    libarcsoft_super_night_se_raw \
    libaualgo_azp_component \
    libaualgo_azp_wrapper \
    libaualgo_foundation \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_audio_session_mediatek \
    libbluetooth_hw_test \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbluetooth_relayer \
    libbluetoothem_mtk \
    libbt-vendor \
    libc++_shared \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.aidepth \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.utility \
    libcamalgo.vaidepth \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera_metadata \
    libcameracustom.camera.3a \
    libcameracustom.eis \
    libcameracustom.imgsensor.core \
    libcameracustom.lens \
    libcameracustom \
    libcomposer_ext \
    libcvsd_mtk \
    libdecrypt \
    libfft_vendor \
    libfgauge_gm30 \
    libforkexecwrap \
    libhfmanager \
    libhfmanagerwrapper \
    libhwm \
    libifcutils_mtk \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkmsetkey \
    libksensor \
    libmipc \
    libmmagent \
    libmpbase \
    libmsbc_mtk \
    libmtk-ril \
    libmtkcam.atmseventmgr \
    libmtkcam.debugwrapper \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam.plugin.tp_supernightraw \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_3rdparty.vidhance \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_cpuctrl_customer \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hal_aidl_common \
    libmtkcam_hal_aidl_device \
    libmtkcam_hal_aidl_provider \
    libmtkcam_hal_aidl_utils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkmipc-ril \
    libmtknetcap \
    libmtkrilutils \
    libmtkspparser \
    libmtkspparser_swb \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libneuralnetworks_sl_driver_mtk_legacy_prebuilt \
    libneuron_wrapper \
    libratconfig \
    librilfusion \
    librt_extamp_intf \
    libsensor_custom \
    libsensorndkbridge \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstfactory-vendor \
    libstorage_otp \
    libtinyxml2-legacy \
    libtrm \
    libvia-ril \
    libviamipc-ril \
    libvidhance \
    libwifitest \
    libwpfa \
    motorola.hardware.camera.imgtuner.aidl-V1-ndk \
    motrilutils \
    arm.graphics-V5-ndk \
    arm.mali.platform-V2-ndk \
    libaiselector \
    libarm_egl_properties_sysprop \
    libarm_gralloc_properties_sysprop \
    libarm_mali_config_sysprops \
    libdpframework \
    libdre \
    libgpudataproducer \
    libhdrvideo \
    libmdla_ut \
    libmmagent \
    libmml \
    libmmlpqImpl \
    libmtk_drvb \
    libneuron_runtime.5 \
    libneuron_runtime \
    libnir_neon_driver \
    libpq_sec \
    libpqparamparser \
    libmtkcam_streaminfo_plugin-p1stt \
    nfc_nci_nxp_snxxx \
    se_extn_client \
    sensors.moto \
    libaecsw \
    libagc1sw \
    libagc2sw \
    libbassboostsw \
    libbundleaidl \
    libdlbvolaidl \
    libdownmixaidl \
    libdynamicsprocessingaidl \
    libenvreverbsw \
    libequalizersw \
    libextensioneffect \
    libhapticgenerator \
    libhapticgeneratoraidl \
    libloudnessenhanceraidl \
    libnssw \
    libpreprocessingaidl \
    libpresetreverbsw \
    libreverbaidl \
    libswdapaidl \
    libswgamedapaidl \
    libswspatializeraidl \
    libvirtualizersw \
    libvisualizeraidl \
    libvolumesw \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.camera.atms-V1-ndk \
    vendor.mediatek.hardware.camera.bgservice-V1-ndk \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal-V1-ndk \
    vendor.mediatek.hardware.camera.postproc-V1-ndk \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq_aidl-V2-ndk \
    vendor.mediatek.hardware.pq_aidl-V4-ndk \
    vendor.mediatek.hardware.pq_aidl-V7-ndk \
    vendor.nxp.nxpese@1.0 \
    vendor.nxp.nxpnfc@2.0 \
    vendor.nxp.nxpnfc_aidl-V1-ndk \
    libapuwareapusys.mtk \
    libapuwareapusys_v2.mtk \
    libapuwarehmp.mtk \
    libapuwareutils.mtk \
    libapuwareutils_v2.mtk \
    libapuwarexrp.mtk \
    libapuwarexrp_v2.mtk \
    libarmnn_ndk.mtk \
    libcmdl_ndk.mtk \
    libmvpu_cic_ci_compiler.mtk \
    libmvpu_cic_ci_compiler_25.mtk \
    libmvpu_clc_14_mvpu_debuginfo_25.mtk \
    libmvpu_clc_14_mvpu_elf_25.mtk \
    libmvpu_clc_14_mvpu_utility_25.mtk \
    libmvpu_clc_mvpu_debuginfo.mtk \
    libmvpu_clc_mvpu_elf.mtk \
    libmvpu_clc_mvpu_utility.mtk \
    libmvpu_config.mtk \
    libmvpu_engine.mtk \
    libmvpu_engine_25.mtk \
    libmvpu_engine_25_pub.mtk \
    libmvpu_engine_pub.mtk \
    libmvpu_pattern.mtk \
    libmvpu_pattern_25.mtk \
    libmvpu_pattern_25_pub.mtk \
    libmvpu_pattern_pub.mtk \
    libmvpu_runtime.mtk \
    libmvpu_runtime_25.mtk \
    libmvpu_runtime_25_pub.mtk \
    libmvpu_runtime_builtin.mtk \
    libmvpu_runtime_builtin_25.mtk \
    libmvpu_runtime_pub.mtk \
    libmvpuop25_mtk_cv.mtk \
    libmvpuop25_mtk_nn.mtk \
    libmvpuop_mtk_cv.mtk \
    libmvpuop_mtk_nn.mtk \
    libneuron_graph_delegate.mtk \
    libneuronusdk_adapter.mtk \
    libnir_neon_driver_ndk.mtk \
    libtflite_mtk.mtk \
    libtflite_mtk \
    vendor.mediatek.hardware.apuware.apusys-V5-ndk \
    vendor.mediatek.hardware.apuware.apusys@1.0 \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.utils-V1-ndk \
    vendor.mediatek.hardware.apuware.utils@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.apuware.xrp-V1-ndk \
    vendor.mediatek.hardware.apuware.xrp@1.0 \
    vendor.mediatek.hardware.apuware.xrp@2.0 \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libsignal \
    libsink-mtk \
    libsource \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    vendor.mediatek.hardware.videotelephony@1.0 \
    EuiccPartnerApp \
    EuiccGoogle \
    HotwordEnrollmentOKGoogleRISCV \
    HotwordEnrollmentXGoogleRISCV \
    MobileFeliCaClient \
    ImsService \
    MtkGbaService \
    moto-telephony \
    com.android.hotwordenrollment.common.util \
    mediatek-ims-base \
    mediatek-ims-oem-plugin \
    android.hardware.drm-service.clearkey.xml \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.secureclock-service.trustonic.xml \
    android.hardware.security.sharedsecret-service.trustonic.xml \
    fingerprint-default.xml \
    manifest_IMoto_AIDL_Fingerprint.xml \
    manifest_hwcomposer.xml \
    memtrack-mediatek.xml \
    motorola.hardware.camera.imgtuner.aidl.xml \
    nfc-service-nxp.xml \
    vibrator-mtk-default.xml \
    autobt \
    bt_dump \
    ccci_mdinit \
    ccci_rpcd \
    conninfra_loader \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    hardware_revisions \
    android.hardware.biometrics.fingerprint-service.goodix \
    android.hardware.drm-service.clearkey \
    android.hardware.gnss-service.mediatek \
    android.hardware.graphics.allocator-V2-service-mediatek \
    android.hardware.memtrack-service.mediatek \
    android.hardware.neuralnetworks-shim-service-mtk-legacy \
    android.hardware.nfc-service.nxp \
    android.hardware.secure_element-service.nxp \
    camerahalserver \
    motorola.hardware.camera.imgtuner.aidl-service \
    mtkfusionrild \
    init.insmod \
    init.mmi.backup.trustlet \
    init.mmi.block_perm \
    init.mmi.boot \
    init.mmi.modem-rfs \
    init.mmi.shutdown \
    init.mmi.touch \
    jpegtool \
    kpgather \
    kpreadwrite \
    mcDriverDaemon \
    mnld \
    motobox \
    mt6660_calibration \
    mtk_agpsd \
    muxreport \
    nvram_daemon \
    nxpnfcinfo \
    pstore_annotate \
    rcs_volte_stack \
    rt5512_calibration \
    sns_mot_client \
    v3avpud \
    volte_clientapi_ua \
    volte_rcs_ua \
    wifi_dump \
    wlan_assistant \
    vtservice

PRODUCT_PACKAGES += \
    vendor_bin_expat \
    vendor_lib64_libDR_so \
    vendor_lib64_libacdk_so
